### ISSUE TITLE
Invalid tool pyzopyunoworkspace: No module named 'sqlite3'

### ISSUE THREAD

**Issue by yardern** [kelsa-pi/PyUNO_Workspace#1]
Thanks for this great software!

I am trying to use it. Followed the wiki. Found:

pyzoPyUNOWorkspace had to be put under **C:\Program Files\pyzo\source\pyzo\tools\**
Because the path mentioned in the wiki does not exist.

When I try to enable pyzoPyUNOWorkspace, I got:
Invalid tool pyzopyunoworkspace: No module named 'sqlite3'

Type "import sqlite3" in the default python shell, no problem.
But in LO shell, I got:
           Traceback (most recent call last):
             File "<console>", line 1, in <module>
             File "C:\Program Files\LibreOffice\program\uno.py", line 345, in _uno_import
               return _builtin_import(name, *optargs, **kwargs)
           ModuleNotFoundError: No module named 'sqlite3'

I am using:
       LibreOffice v7.1.0.3 (include python 3.8.4) 64bit
       Windows 10 64bit
       Python 3.8.4 64bit
       pyzo 4.11.2 win32, its logger says Python 3.9.0 on win32.

Am I doing something wrong please?

Best regards

Yardern

**Comment by kelsa-pi** [comment]
Hi,
Thanks for the input.
I will look into it
Best

**Comment by kelsa-pi** [comment]
Hi,
if you have standard Python exe (I suppose Python 3.8.4 64bit from above) then run pip install pyzo in command window.

There is a problem with pyzo windows zip files (tested only 64bit).
I opened issue [#743](https://github.com/pyzo/pyzo/issues/743)
Best
